### ISSUE TITLE
Problem with component auto playing

### ISSUE THREAD

**Issue by david95alex** [RealCoolSnow/vue3-audio-player#3]
Hi, i'm using the vue3-audio-player for a project, and I'm having this problem when any form in the page gets an input, the audio player starts playing automatically. Can you provide any help?

**Comment by RealCoolSnow** [comment]
hi，can you provide a snippet of your code?

**Comment by linshimao** [comment]
建议支持配置是否自动播放和禁止拖动进度条等等...

**Comment by hanzhenfang** [comment]
I fix this issue. @RealCoolSnow
